"""add columns to yield

Revision ID: 0a687f064d11
Revises: db535ce573e5
Create Date: 2022-12-22 20:51:08.424219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a687f064d11'
down_revision = 'db535ce573e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('season', sa.String(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_yield_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_yield_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yield_year'))
        batch_op.drop_index(batch_op.f('ix_yield_season'))
        batch_op.drop_column('season')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
