"""remove account table

Revision ID: 296887d5f88c
Revises: 2d333928b385
Create Date: 2022-12-24 17:06:43.886321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '296887d5f88c'
down_revision = '2d333928b385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # with op.batch_alter_table('account', schema=None) as batch_op:
    #     batch_op.drop_index('ix_account_field')

    # op.drop_table('account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field', mysql.ENUM('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti'), nullable=True),
    sa.Column('type', mysql.ENUM('expense', 'income'), nullable=True),
    sa.Column('category', mysql.ENUM('labour', 'food', 'rental', 'repair', 'maintenance', 'fuel', 'paddy seeds', 'lentil seeds', 'fertilizer', 'pesticides', 'herbicides', 'paddy sale', 'lentil sale'), nullable=True),
    sa.Column('operation', mysql.ENUM('field preparation', 'sowing', 'transplanting', 'spraying', 'field maintenance', 'weeding', 'harvesting', 'supplies', 'equipments'), nullable=True),
    sa.Column('item', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('rate', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('cost', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], name='account_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field'], ['fields.location'], name='account_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('ix_account_field', ['field'], unique=False)

    # ### end Alembic commands ###
