"""fix location field in all tables

Revision ID: 2d333928b385
Revises: df5c3ea25761
Create Date: 2022-12-24 12:58:53.667682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d333928b385'
down_revision = 'df5c3ea25761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_location', sa.Enum('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard', name='field_location'), nullable=True))
        batch_op.create_foreign_key(None, 'fields', ['field_location'], ['location'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('sowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Enum('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard', name='field_location'), nullable=True))
        batch_op.create_index(batch_op.f('ix_sowing_location'), ['location'], unique=False)
        batch_op.create_foreign_key(None, 'fields', ['location'], ['location'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Enum('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard', name='field_location'), nullable=True))
        batch_op.create_index(batch_op.f('ix_yield_location'), ['location'], unique=False)
        batch_op.create_foreign_key(None, 'fields', ['location'], ['location'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_yield_location'))
        batch_op.drop_column('location')

    with op.batch_alter_table('sowing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sowing_location'))
        batch_op.drop_column('location')

    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('field_location')

    # ### end Alembic commands ###
