"""change column size

Revision ID: 305036ebf916
Revises: 296887d5f88c
Create Date: 2023-01-26 01:13:06.458266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '305036ebf916'
down_revision = '296887d5f88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('disease_resistance',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('pest_resistance',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('pest_resistance',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('disease_resistance',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
