"""rmv year and season

Revision ID: 410af39f2703
Revises: 0a687f064d11
Create Date: 2022-12-22 22:34:27.461612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '410af39f2703'
down_revision = '0a687f064d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.drop_index('ix_yield_season')
        batch_op.drop_index('ix_yield_year')
        batch_op.drop_column('year')
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('year', mysql.VARCHAR(length=4), nullable=False))
        batch_op.create_index('ix_yield_year', ['year'], unique=False)
        batch_op.create_index('ix_yield_season', ['season'], unique=False)

    # ### end Alembic commands ###
