"""change name column size

Revision ID: 57011d15eef4
Revises: 94635c4dd9dc
Create Date: 2023-01-26 01:17:43.090150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57011d15eef4'
down_revision = '94635c4dd9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
