"""use field id as FK

Revision ID: 60c4474e0a49
Revises: ead03bff597e
Create Date: 2023-01-31 16:25:59.429735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60c4474e0a49'
down_revision = 'ead03bff597e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key(None, 'fields', ['location_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('accounts_link', schema=None) as batch_op:
        batch_op.drop_constraint('accounts_link_ibfk_1', type_='foreignkey')
        batch_op.drop_column('field_id')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_entry_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key(None, 'fields', ['location_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.drop_constraint('fkc_yield_sowing_id', type_='foreignkey')
        batch_op.drop_index('ix_yield_sowing_id')
        batch_op.drop_column('sowing_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sowing_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fkc_yield_sowing_id', 'sowing', ['sowing_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('ix_yield_sowing_id', ['sowing_id'], unique=False)

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_entry_location_id'))
        batch_op.drop_column('location_id')

    with op.batch_alter_table('accounts_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('accounts_link_ibfk_1', 'fields', ['field_id'], ['id'])

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_location_id'))
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
