"""add field to accountentry

Revision ID: 6194eeffc1c5
Revises: 35ae847974d4
Create Date: 2023-01-31 11:57:55.567214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6194eeffc1c5'
down_revision = '35ae847974d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.Enum('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard', name='field_location'), nullable=True))
        batch_op.create_index(batch_op.f('ix_entry_field'), ['field'], unique=False)
        batch_op.create_foreign_key(None, 'fields', ['field'], ['location'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_entry_field'))
        batch_op.drop_column('field')

    # ### end Alembic commands ###
