"""add year-season to yield

Revision ID: 89739dae3f7b
Revises: 410af39f2703
Create Date: 2022-12-23 14:20:32.974072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89739dae3f7b'
down_revision = '410af39f2703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('season', sa.String(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_yield_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_yield_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yield_year'))
        batch_op.drop_index(batch_op.f('ix_yield_season'))
        batch_op.drop_column('season')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
