"""add variety duration to sowing

Revision ID: 912d81a04a14
Revises: 89739dae3f7b
Create Date: 2022-12-23 15:02:33.437958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912d81a04a14'
down_revision = '89739dae3f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sowing', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
