"""change habit column size

Revision ID: 94635c4dd9dc
Revises: 305036ebf916
Create Date: 2023-01-26 01:16:44.152667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94635c4dd9dc'
down_revision = '305036ebf916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('habit',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety', schema=None) as batch_op:
        batch_op.alter_column('habit',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
