"""change table name

Revision ID: ceeca6cdafaf
Revises: 912d81a04a14
Create Date: 2022-12-23 23:45:26.157107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceeca6cdafaf'
down_revision = '912d81a04a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index('ix_equipment_location')
        batch_op.drop_index('ix_equipment_nickname')

    op.drop_table('equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('type', mysql.ENUM('motorbike', 'pumps', 'sprayer', 'tractor', 'transplanter'), nullable=False),
    sa.Column('geotag', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('location', mysql.ENUM('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'none'), nullable=False),
    sa.Column('last_service', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_nickname', ['nickname'], unique=False)
        batch_op.create_index('ix_equipment_location', ['location'], unique=False)

    # ### end Alembic commands ###
