"""change column names in envdata

Revision ID: d1fe9353b3cc
Revises: 2e6ba70a5afc
Create Date: 2023-04-01 23:11:30.530185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fe9353b3cc'
down_revision = '2e6ba70a5afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('moisture_category', sa.String(length=10), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envdata', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('moisture_category')
        batch_op.drop_column('day')
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
