"""change extent to field_extent

Revision ID: ea3776fe7ca7
Revises: a6caa9cb0937
Create Date: 2022-12-14 22:36:58.026655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea3776fe7ca7'
down_revision = 'a6caa9cb0937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_extent', sa.Float(), nullable=True))
        batch_op.drop_column('extent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extent', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('field_extent')

    # ### end Alembic commands ###
