"""add account association table

Revision ID: ead03bff597e
Revises: 6194eeffc1c5
Create Date: 2023-01-31 16:04:54.872652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead03bff597e'
down_revision = '6194eeffc1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('accounts_ibfk_2', type_='foreignkey')
        batch_op.drop_index('ix_accounts_field')
        batch_op.drop_column('field')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint('entry_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_entry_field')
        batch_op.drop_column('field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sowing_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fkc_yield_sowing_id', 'sowing', ['sowing_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('ix_yield_sowing_id', ['sowing_id'], unique=False)

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', mysql.ENUM('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard'), nullable=True))
        batch_op.create_foreign_key('entry_ibfk_1', 'fields', ['field'], ['location'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('ix_entry_field', ['field'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', mysql.ENUM('tgudi', 'pallachi', 'potteri', 'pokonanthoki', 'mannamuti', 'trichy-home1', 'trichy-home2', 'house-yard'), nullable=True))
        batch_op.create_foreign_key('accounts_ibfk_2', 'fields', ['field'], ['location'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('ix_accounts_field', ['field'], unique=False)
    # ### end Alembic commands ###
